### ISSUE TITLE
Is this email address outdated? 

### ISSUE THREAD

**Issue by denkeste** [cyrdam/pnpm-monorepo-starter#4]
Hey Damian! 

I believe this email address to be outdated: 
https://github.com/cyrdam/pnpm-monorepo-starter/blob/4043c91549f5e066ee6dee20abc7affb3e58a4cf/package.json#L16C2-L16C2

Could you please check?

**Comment by cyrdam** [comment]
Hi @denkeste, you are right, I updated the email. Thanks for the hint.

Fixed with: https://github.com/cyrdam/pnpm-monorepo-starter/commit/2e8df71a2949259419cc1b02bad691263c8557c0
